name: Feature Request
description: Create a feature request for Umami
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true