name: Create docker images

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
      add-latest:
        type: boolean
        description: Add latest tag
        required: false

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db-type: [postgresql, mysql]

    steps:
      - uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image for ${{ matrix.db-type }}
        with:
          image: umami
          tags: ${{ matrix.db-type }}-${{ inputs.version }}
          addLatest: ${{ inputs.add-latest }}
          buildArgs: DATABASE_TYPE=${{ matrix.db-type }}
          registry: ghcr.io/${{ github.actor }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
